### ISSUE TITLE
Download and copy this repository to `/site/plugins/kirby-tidy-html`

### ISSUE THREAD

**Issue by timotheegoguely** [dgsiegel/kirby-tidy-html#1]
Would it be possible to install your plugin simply by copying the folder into the `site/plugins/kirby-tidy-html` folder, or installing it using Composer is the only workaround?

Thanks for your work, this a very good Kirby plugin idea.

**Comment by dgsiegel** [comment]
> Would it be possible to install your plugin simply by copying the folder into the `site/plugins/kirby-tidy-html` folder

Sure, just copy all files into `site/plugins/kirby-tidy-html` (or whatever name you wanna use), and configure the plugin accordingly.

**Comment by timotheegoguely** [comment]
Cool! So even if it seems obvious to you, I think you should mention it in the Installation part your `README`.
Here is a exemple from getkirby/staticache official plugin: https://github.com/getkirby/staticache?tab=readme-ov-file#download

**Comment by dgsiegel** [comment]
Done, thanks!
